name: Create Drafter
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create_draft:
    if: github.event.pull_request.merged == true
    runs-on:
      group: default
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GIT_APP_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}
          owner: SallaApp

      - uses: SallaApp/.CI/create-draft@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN_PRIVATE }}
          telegram_group: ${{ secrets.TELEGRAM_TO_PRIVATE }}
          autorelease_enabled: "true"
          force_push_tag: "true"
          github_tag_token: ${{ steps.app-token.outputs.token }}
