name: Test
on:
  push:
    branches:
      - master

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run_tests:
    name: "Testing Ready"
    runs-on:
      group: default

    steps:
      - uses: SallaApp/.CI/mf-deployer/lint@master
        with:
          npm_token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          codacy_api_token: ${{ secrets.CODACY_API_TOKEN }}
